// this code is created by Palash Jana
//This code sends sensor data like temparature & Humidity every minutes
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <UniversalTelegramBot.h>
#include <DHT.h>

// Wi-Fi credentials
const char* ssid = "hotspot_name";
const char* password = "hotspot_password";

// DHT settings
#define DHTPIN 13 // Please correct the pin as you select
#define DHTTYPE DHT11
DHT dht(DHTPIN, DHTTYPE);

// Telegram
#define BOT_TOKEN "Add_Telegram_bot_token"//This bot token generated by BotFather in Telegram
#define CHAT_ID "Bot_Chat_ID"

WiFiClientSecure client;
UniversalTelegramBot bot(BOT_TOKEN, client);

void setup() {
  Serial.begin(115200);
  dht.begin();

  // Connect to Wi-Fi
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500); Serial.print(".");
  }
  Serial.println("\nWiFi connected");

  // Required for HTTPS
  client.setInsecure();  // Accept all certs
}

void loop() {
  float temp = dht.readTemperature();
  float hum = dht.readHumidity();

  if (!isnan(temp) && !isnan(hum)) {
    String msg = "📡 ESP32 Alert:\n";
    msg += "🌡 Temp: " + String(temp) + " °C\n";
    msg += "💧 Humidity: " + String(hum) + " %";

    Serial.println("Sending Telegram message...");
    bot.sendMessage(CHAT_ID, msg, "");
  } else {
    Serial.println("❌ Failed to read DHT11");
  }

  delay(10000); // Wait 60 sec before next message
}